model_params:

  Decision_Tree:
    criterion:
      - gini
      - entropy
      - log_loss
    splitter:
      - best
      - random
    max_features:
      - sqrt
      - log2


  Random_Forest:
    criterion:
      - gini
      - entropy
      - log_loss
    max_features:
      - sqrt
      - log2
      - None
    n_estimators:
      - 8
      - 16
      - 32
      - 128
      - 256
  
  Gradient_Boosting:
    learning_rate:
      - .1
      - .01
      - .05
      - .001
    subsample:
      - 0.6
      - 0.7
      - 0.75
      - 0.85
      - 0.9
    n_estimators:
      - 8
      - 16
      - 32
      - 64
      - 125
      - 256

  Logistic_Regression: {}

  Ada_Boost:
    learning_rate:
      - .1
      - .01
      - .001
    n_estimators:
      - 8
      - 16
      - 32
      - 64
      - 128
      - 256
      

  